# TCL File Generated by Component Editor 15.0
# Wed Mar 09 18:37:05 PST 2016
# DO NOT MODIFY


# 
# accelerator "accelerator" v1.0
#  2016.03.09.18:37:05
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module accelerator
# 
set_module_property DESCRIPTION ""
set_module_property NAME accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME accelerator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL accelerator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file accelerator.v VERILOG PATH accelerator.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL accelerator
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file accelerator.v VERILOG PATH accelerator.v


# 
# parameters
# 
add_parameter IDLE STD_LOGIC_VECTOR 1
set_parameter_property IDLE DEFAULT_VALUE 1
set_parameter_property IDLE DISPLAY_NAME IDLE
set_parameter_property IDLE TYPE STD_LOGIC_VECTOR
set_parameter_property IDLE UNITS None
set_parameter_property IDLE ALLOWED_RANGES 0:127
set_parameter_property IDLE HDL_PARAMETER true
add_parameter READ STD_LOGIC_VECTOR 2
set_parameter_property READ DEFAULT_VALUE 2
set_parameter_property READ DISPLAY_NAME READ
set_parameter_property READ TYPE STD_LOGIC_VECTOR
set_parameter_property READ UNITS None
set_parameter_property READ ALLOWED_RANGES 0:127
set_parameter_property READ HDL_PARAMETER true
add_parameter WRITE STD_LOGIC_VECTOR 4
set_parameter_property WRITE DEFAULT_VALUE 4
set_parameter_property WRITE DISPLAY_NAME WRITE
set_parameter_property WRITE TYPE STD_LOGIC_VECTOR
set_parameter_property WRITE UNITS None
set_parameter_property WRITE ALLOWED_RANGES 0:127
set_parameter_property WRITE HDL_PARAMETER true
add_parameter WRITE_DONE STD_LOGIC_VECTOR 8
set_parameter_property WRITE_DONE DEFAULT_VALUE 8
set_parameter_property WRITE_DONE DISPLAY_NAME WRITE_DONE
set_parameter_property WRITE_DONE TYPE STD_LOGIC_VECTOR
set_parameter_property WRITE_DONE UNITS None
set_parameter_property WRITE_DONE ALLOWED_RANGES 0:127
set_parameter_property WRITE_DONE HDL_PARAMETER true
add_parameter WAIT_VALID STD_LOGIC_VECTOR 16
set_parameter_property WAIT_VALID DEFAULT_VALUE 16
set_parameter_property WAIT_VALID DISPLAY_NAME WAIT_VALID
set_parameter_property WAIT_VALID TYPE STD_LOGIC_VECTOR
set_parameter_property WAIT_VALID UNITS None
set_parameter_property WAIT_VALID ALLOWED_RANGES 0:127
set_parameter_property WAIT_VALID HDL_PARAMETER true
add_parameter SDRAM_BASE STD_LOGIC_VECTOR 3221225472
set_parameter_property SDRAM_BASE DEFAULT_VALUE 3221225472
set_parameter_property SDRAM_BASE DISPLAY_NAME SDRAM_BASE
set_parameter_property SDRAM_BASE TYPE STD_LOGIC_VECTOR
set_parameter_property SDRAM_BASE UNITS None
set_parameter_property SDRAM_BASE ALLOWED_RANGES 0:17179869183
set_parameter_property SDRAM_BASE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master read_n read_n Output 1
add_interface_port avalon_master write_n write_n Output 1
add_interface_port avalon_master chipselect chipselect Output 1
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master address address Output 32
add_interface_port avalon_master byteenable byteenable Output 2
add_interface_port avalon_master readdatavalid readdatavalid Input 1
add_interface_port avalon_master readdata readdata Input 16
add_interface_port avalon_master writedata writedata Output 16

